Function vrdtvsp_create_custom_QSF_vbscript_vrd_5_AND_6( byVAL ccqsfs_vrd_version )
	' Create a custom QSF Script for use with VRD v6
	' Return the Absolute filename of the script
	Dim ccqsfs_Absolute_script_name
	Dim ccqsfs_object
	Dim ccqsfs_status
	Dim ccqsfs(), i, c
	'
	ccqsfs_Absolute_script_name = vrdtvsp_gimme_a_temporary_absolute_filename("vrdtvsp_custom_vrd" & ccqsfs_vrd_version & "_QSF_script-" & vrdtvsp_run_datetime) & ".vbs"
	c = -1 ' base 0
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Option Explicit"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' File: """ & ccqsfs_Absolute_script_name & """"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Example VRD VBScript to do QSF with QSF Profile and save an XML file of characteristics"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Args(0) is input video file path - a fully qualified path name"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Args(1) is path/name of output QSF'd file - a fully qualified path name"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Args(2) is name of QSF Output Profile created in VRD v6"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Args(3) is path/name of a file of XML associated with the output QSF'd file - a fully qualified path name"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Note: An additional file is created, with the same full filename/ext as Args(1) with .xml added on the end."
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'       This .xml file contains complete info for the most recently completed output file "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'       (hopefully the QSF) from a call to OutputGetCompletedInfo() or FileGetOpenedFileProgramInfo()."
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'       With any luck, the timing of concurrent workflow doing calls works out for us, although we should still check the filename from the XML."
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Example Returned xml string: from VideoReDo.FileGetOpenedFileProgramInfo()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' This is a well-formed single-item XML string, which make it really easy to find things"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'<VRDProgramInfo>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <FileName d=""Name"">somefilename.qsf.vrd6.mp4</FileName>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <FileSize f=""0.029 GB"" d=""Size"">28519136</FileSize>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <ProgramDuration f=""00:01:04.84"" d=""Duration"" total_frames=""1622"">5835601</ProgramDuration>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <FileType d=""Mux type"">MP4</FileType>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <Video>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <Encoding>H.264</Encoding>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <VideoStreamID>x201</VideoStreamID>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <FrameRate f=""25.00 fps"" d=""Frame rate"">25.000000</FrameRate>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <constant_frame_rate_flag d=""Frame rate flag"">Constant</constant_frame_rate_flag>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <EncodingDimensions d=""Encoding size"" width=""1920"" height=""1080"">1920 x 1080</EncodingDimensions>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <AspectRatio d=""Aspect ratio"">16:9</AspectRatio>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <HeaderBitRate f=""25.000 Mbps"" d=""Header bit rate"">25000000</HeaderBitRate>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <VBVBufferSize f=""572 KBytes"" d=""VBV buffer"">572</VBVBufferSize>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <Profile>High/4.0</Profile>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <Progressive f=""Interlaced"">False</Progressive>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <Chroma chroma_value=""1"">4:2:0</Chroma>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <EntropyCodingMode d=""Entropy mode"">CABAC</EntropyCodingMode>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <EstimatedVideoBitrate f=""2.992 Mbps"" d=""Bit rate"">2992213</EstimatedVideoBitrate>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  </Video>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <AudioStreams>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <AudioStream StreamNumber=""1"" Primary=""true"">"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <AudioCodec d=""Codec"">AC3</AudioCodec>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <Format>AC3 stream</Format>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <AudioChannels d=""Channels"">5.1</AudioChannels>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <Language>eng</Language>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <PID>x202</PID>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <PESStreamId d=""PES Stream Id"">xBD</PESStreamId>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <AudioBitRate f=""448 Kbps"" d=""Bit rate"">448000</AudioBitRate>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <AudioSampleRate d=""Sampling rate"">48000</AudioSampleRate>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    <BitsPerSample d=""Sample size"" f=""16 bits"">16</BitsPerSample>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    </AudioStream>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'    </AudioStreams>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <SubtitleStreams/>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'</VRDProgramInfo>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Example Returned xml string: from VideoReDo.OutputGetCompletedInfo()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' VideoReDo.OutputGetCompletedInfo() MUST be called immediately AFTER a QSF FileSaveAs and BEFORE the .Close of the source file for the QSF"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' This is a well-formed single-item XML string, which make it really easy to find things"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'<VRDOutputInfo outputFile=""G:\HDTV\000-TO-BE-PROCESSED\zzz-TEST\VRDTVSP-Source\News-National_Nine_News_Afternoon_Edition.2021-02-05.ts.QSF"">"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <OutputType desc=""Output format:"" hidden=""1"">MP4</OutputType>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <OutputDurationSecs desc=""Video length:"" val_type=""int"" hidden=""1"">65</OutputDurationSecs>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <OutputDuration desc=""Video length:"">00:01:05</OutputDuration>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <OutputSizeMB desc=""Video size:"" val_type=""int"" val_format=""%dMB"">27</OutputSizeMB>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <OutputSceneCount desc=""Output scenes:"" val_type=""int"">1</OutputSceneCount>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <VideoOutputFrameCount desc=""Video output frames:"" val_type=""int"">1625</VideoOutputFrameCount>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <AudioOutputFrameCount desc=""Audio output frames:"" val_type=""int"">2033</AudioOutputFrameCount>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <ProcessingTimeSecs desc=""Processing time (secs):"" val_type=""int"">1</ProcessingTimeSecs>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <ProcessedFramePerSec desc=""Processed frames/sec:"" val_type=""float"" val_format=""%.2f"">1625.000000</ProcessedFramePerSec>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <ActualVideoBitrate desc=""Actual Video Bitrate:"" desc_format=""%24s"" val_type=""float"" val_format=""%0.2f Mbps"">2.912357</ActualVideoBitrate>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <lkfs_values hidden=""1""/>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'  <audio_level_changes hidden=""1""/>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'</VRDOutputInfo>"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim Args, argCount"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim inputFile"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim qsfFile"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim QSF_profile_name"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim xmlFile"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim VideoReDoSilent"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim VideoReDo"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim openflag, closeflag, outputOK, OutputGetState, percentComplete"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim percent"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim i, profile_count, QSF_profile_count, matching_QSF_profile, a_profile_name, is_QSF"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim QSF_Profile_Names()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim xml_string, xml_string_openedfile, xml_string_completedfile"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim xmlDoc,	xml_status, xml_objErr, xml_errorCode, xml_reason"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim actual_outputFile, actual_VideoOutputFrameCount, actual_ActualVideoBitrate"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim estimated_outputFile, estimated_VideoOutputFrameCount, estimated_ActualVideoBitrate"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Dim fso, fileObj"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set Args = Wscript.Arguments"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "argCount = Wscript.Arguments.Count"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "If argCount <> 4 Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: ERROR: arg count should be 3, but is "" & argCount)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF:			Args(0) is the fully qualified path/name of the input video file"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF:			Args(1) is the fully qualified path/name of the output project (.vprj) file."")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF:			Args(2) is name of QSF Output Profile already created and saved inside VRD v6"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF:			Args(3) ist he fully qualified path/name of an output XML file of QSF file characteristics."")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.Quit 5"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "inputFile = Args(0)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "qsfFile = Args(1)				' including extension .vprj"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "QSF_profile_name = Args(2)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xmlFile = Args(3)				' including extension .xml"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	If ccqsfs_vrd_version = 5 Then
		c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set VideoReDoSilent = WScript.CreateObject(""VideoReDo5.VideoReDoSilent"")"
	ElseIf ccqsfs_vrd_version = 6 Then
		c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set VideoReDoSilent = WScript.CreateObject(""VideoReDo6.VideoReDoSilent"")"
	Else
		WScript.StdOut.WriteLine("VRDTVSP vrdtvsp_create_custom_QSF_vbscript_vrd_5_AND_6 - Error - VRD version must be 5 or 6, not """ & ccqsfs_vrd_version & """... Aborting ...")
		Wscript.Echo "Error 17 = cannot perform the requested operation"
		On Error goto 0
		WScript.Quit 17 ' Error 17 = cannot perform the requested operation
	End If
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set VideoReDo = VideoReDoSilent.VRDInterface"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "VideoReDo.ProgramSetAudioAlert(False)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "QSF_profile_count = 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "profile_count = VideoReDo.ProfilesGetCount()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "For i = 0 to profile_count-1"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	a_profile_name = VideoReDo.ProfilesGetProfileName( i )"
	If ccqsfs_vrd_version = 5 Then
		c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	is_QSF = True"
	ElseIf ccqsfs_vrd_version = 6 Then
		c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	is_QSF = NOT VideoReDo.ProfilesGetProfileIsAdScan( i )"
	End If
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	If ( is_QSF ) Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		QSF_profile_count = QSF_profile_count + 1"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		ReDim Preserve QSF_Profile_Names(QSF_profile_count-1) ' base 0, remember"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		QSF_Profile_Names(QSF_profile_count-1) = a_profile_name"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "If QSF_profile_count < 1 Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: ERROR: no VRD QSF profiles were returned by VRD"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: Exiting with errorlevel code 5"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	VideoReDo.ProgramExit()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: Exiting with errorlevel code 5"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.Quit 5"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "matching_QSF_profile = False"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "For i = 0 to (QSF_profile_count-1)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	If QSF_profile_name = QSF_Profile_Names(i) Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		matching_QSF_profile = True"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		Exit For"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "If NOT matching_QSF_profile Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: ERROR: no VRD QSF profile was located matching your specified profile: """""" & QSF_profile_name & """""""")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	For i = 0 to profile_count-1"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		a_profile_name = VideoReDo.ProfilesGetProfileName( i )"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		is_QSF = NOT VideoReDo.ProfilesGetProfileIsAdScan( i )"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		If ( is_QSF ) Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "			QSF_profile_count = QSF_profile_count + 1"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "			Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: Profile ("" & i & "")="""""" & a_profile_name & """""" is an QSF profile"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: QSF Profile count: "" & QSF_profile_count )"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: Exiting with errorlevel code 5"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	VideoReDo.ProgramExit()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: Exiting with errorlevel code 5"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.Quit 5"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "openflag = VideoReDo.FileOpen(inputFile, True) ' True means QSF mode" 
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "If openflag = False Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: ERROR: VideoReDo failed to open file: """""" & inputFile & """""""")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	VideoReDo.ProgramExit()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: Exiting with errorlevel code 5"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.Quit 5"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "outputOK = VideoReDo.FileSaveAs(qsfFile, QSF_profile_name) ' save the QSF file"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "If NOT outputOK = True Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: ERROR: VideoReDo failed to create QSF file: """""" & qsfFile & """""" using profile:"""""" & QSF_profile_name & """""""")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	closeflag = VideoReDo.FileClose()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	VideoReDo.ProgramExit()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: Exiting with errorlevel code 5"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.Quit 5"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.Write(""VRDTVSP_VRD_QSF: working: "")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'Wscript.StdOut.Write(""VRDTVSP_VRD_QSF: Percent Complete: "")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "OutputGetState = VideoRedo.OutputGetState()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "While( OutputGetState <> 0 )"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		percentComplete = CLng(VideoReDo.OutputGetPercentComplete())"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'if NOT err.number = 0 then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'	percentComplete = 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'end if"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'Wscript.StdOut.Write("" "" & percent & ""% "")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.StdOut.Write( ""."" & OutputGetState)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.Sleep 2000"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	OutputGetState = VideoRedo.OutputGetState()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wend"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine( ""."" & OutputGetState & ""."")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: QSF 100% Complete."")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Grab the *Actual* info about the ""VRD latest save"" and hope it is the QSF file)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_string_completedfile = """" "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_string_completedfile = VideoReDo.OutputGetCompletedInfo() ' which is the most recently completed output file (hopefully the QSF file) https://www.videoredo.com/TVSuite_Application_Notes/output_complete_info_xml_forma.html"" "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "closeflag = VideoReDo.FileClose()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine("" QSF 100% Complete."")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Grab the *Estimated* info about the QSF file by a quick open and close"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "openflag = VideoReDo.FileOpen(qsfFile, False)' True means QSF mode"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_string_openedfile = """" "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_string_openedfile = VideoReDo.FileGetOpenedFileProgramInfo() ' https://www.videoredo.com/TVSuite_Application_Notes/program_info_xml_format.html"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "closeflag = VideoReDo.FileClose()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: xml_string_completedfile="") "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(xml_string_completedfile) "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: xml_string_openedfile="") "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(xml_string_openedfile) "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "''''' Get Actual data obtained during the QSF process"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set xmlDoc = WScript.CreateObject(""Msxml2.DOMDocument.6.0"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xmlDoc.async = False"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_status = xmlDoc.loadXML(xml_string_completedfile) "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set xml_objErr = xmlDoc.parseError"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_errorCode = xml_objErr.errorCode"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_reason = xml_objErr.reason"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set xml_objErr = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Err.clear"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0 "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "If NOT xml_status Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Set xmlDoc = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	WScript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: ABORTING: Failed to load xml_string_completedfile="" & xml_string_completedfile)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	WScript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: ABORTING: xml_status: "" & xml_status & "" XML error: "" & xml_errorCode & "" : "" & xml_reason)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.Echo ""Error 17 = cannot perform the requested operation"""
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	On Error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	WScript.Quit 17 ' Error 17 = cannot perform the requested operation"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "actual_outputFile = gimme_xml_named_attribute(xmlDoc, ""//VRDOutputInfo"", ""outputFile"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "actual_VideoOutputFrameCount = gimme_xml_named_value(xmlDoc, ""//VRDOutputInfo/VideoOutputFrameCount"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "actual_ActualVideoBitrate = gimme_xml_named_value(xmlDoc, ""//VRDOutputInfo/ActualVideoBitrate"") ' decimal number in Mbps"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "If actual_ActualVideoBitrate = """" Then actual_ActualVideoBitrate = 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "actual_ActualVideoBitrate = CLng(CDbl(actual_ActualVideoBitrate) * CDbl(1000000.0)) ' convert from dedcimal Mpbs to bps"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set xmlDoc = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "''''' Get Estimated data from a quick open and close of the the QSF file"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set xmlDoc = WScript.CreateObject(""Msxml2.DOMDocument.6.0"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xmlDoc.async = False"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_status = xmlDoc.loadXML(xml_string_openedfile) "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set xml_objErr = xmlDoc.parseError"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_errorCode = xml_objErr.errorCode"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "xml_reason = xml_objErr.reason"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set xml_objErr = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Err.clear"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0 "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "If NOT xml_status Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Set xmlDoc = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	WScript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: ABORTING: Failed to load xml_string_openedfile="" & xml_string_openedfile)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	WScript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: ABORTING: xml_status: "" & xml_status & "" XML error: "" & xml_errorCode & "" : "" & xml_reason)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Wscript.Echo ""Error 17 = cannot perform the requested operation"""
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	On Error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	WScript.Quit 17 ' Error 17 = cannot perform the requested operation"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "estimated_outputFile = gimme_xml_named_value(xmlDoc, ""//VRDProgramInfo/FileName"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "estimated_VideoOutputFrameCount = gimme_xml_named_attribute(xmlDoc, ""//VRDProgramInfo/ProgramDuration"", ""total_frames"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "estimated_ActualVideoBitrate = gimme_xml_named_value(xmlDoc, ""//VRDProgramInfo/Video/EstimatedVideoBitrate"") ' decimal number in Mbps"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set xmlDoc = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "' Write our own version of the XML values to the specified XML file so that the calling script can read them later"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set fso = CreateObject(""Scripting.FileSystemObject"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set fileObj = fso.CreateTextFile(xmlFile, True, False) ' *** vapoursynth fails with unicode input file *** [ filename, Overwrite[, Unicode]])"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "If Ucase(actual_outputFile) = Ucase(qsfFile) Then ' Use the Actual QSF values"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""<QSFinfo>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""   <type>actual</actual_type>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""   <outputFile>"""""" & actual_outputFile & """"""</outputFile>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""   <VideoOutputFrameCount>"" & actual_VideoOutputFrameCount & ""</VideoOutputFrameCount>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""   <Bitrate>"" & actual_ActualVideoBitrate & ""<Bitrate>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""</QSFinfo>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Else ' Use the Estimated QSF values"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""   <QSFinfo>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""   <type>estimated</type>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""   <outputFile>"""""" & estimated_outputFile & """"""</outputFile>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""   <VideoOutputFrameCount>"" & estimated_VideoOutputFrameCount & ""</VideoOutputFrameCount>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""   <Bitrate>"" & estimated_ActualVideoBitrate & ""<Bitrate>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	fileObj.WriteLine(""</QSFinfo>"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "fileObj.close"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set fileObj = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Set fso = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: actual_outputFile="""""" & actual_outputFile & """""""") "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: actual_VideoOutputFrameCount="" & actual_VideoOutputFrameCount) "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: actual_ActualVideoBitrate="" & actual_ActualVideoBitrate) "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: estimated_outputFile="""""" & estimated_outputFile & """""""") "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: estimated_VideoOutputFrameCount="" & estimated_VideoOutputFrameCount) "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: estimated_ActualVideoBitrate="" & estimated_ActualVideoBitrate) "
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.StdOut.WriteLine(""VRDTVSP_VRD_QSF: Exiting"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "'on error resume Next"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "VideoReDo.ProgramExit()"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "on error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Wscript.Quit 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Function gimme_xml_named_value (xmlDoc_object, byVAL xml_item_name) ' assumes the xml doc is already loaded in xmlDoc_object"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'	Parameters:"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'		xmlDoc_object 	the DOM xml object with the xml string already loaded"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'		xml_item_name 	a string like //VRDProgramInfo/Video/EstimatedVideoBitrate"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Dim item_nNode, item_text"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Set item_nNode = xmlDoc_object.selectsinglenode(xml_item_name) ' eg '//VRDProgramInfo/Video/EstimatedVideoBitrate' CAREFUL, this is case sensitive"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	If item_nNode is Nothing Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		WScript.StdOut.WriteLine(""ABORTING: Could not find XML node "" & xml_item_name & "" in xmlDoc_object"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		Wscript.Echo ""Error 17 = cannot perform the requested operation"""
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		Set xmlDoc_object = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		On Error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		WScript.Quit 17 ' Error 17 = cannot perform the requested operation exit with an error ... soft or hard ?"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	gimme_xml_named_value = item_nNode.text ' eg the text for that item //VideoReDoProject/EstimatedVideoBitrate"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End Function"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "Function gimme_xml_named_attribute (xmlDoc_object, byVAL xml_item_name, byVAL xml_item_attribute_name)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'	Parameters:"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'		xmlDoc_object 	the DOM xml object with the xml string already loaded"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	'		xml_item_name 	a string like //VideoReDoProject/EncodingDimensions"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Dim item_nNode, item_text"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	Set item_nNode = xmlDoc_object.selectsinglenode(xml_item_name) ' eg '//VideoReDoProject/EncodingDimensions' CAREFUL, this is case sensitive"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	If item_nNode is Nothing Then"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		WScript.StdOut.WriteLine(""ABORTING: Could not find XML node "" & xml_item_name & "" in xmlDoc_object"")"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		Wscript.Echo ""Error 17 = cannot perform the requested operation"""
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		Set xmlDoc_object = Nothing"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		On Error goto 0"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "		WScript.Quit 17 ' Error 17 = cannot perform the requested operation exit with an error ... soft or hard ?"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	End If"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	item_text = item_nNode.text ' eg the text for that item //VideoReDoProject/EncodingDimensions"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "	gimme_xml_named_attribute = item_nNode.getAttribute(xml_item_attribute_name)"
	c=c+1 : ReDim Preserve ccqsfs(c) : ccqsfs(c) = "End Function"
	' Create the new custom QSF script in the nominated file from the array above
	ccqsfs_status = vrdtvsp_delete_a_file(ccqsfs_Absolute_script_name, True) 	' delete the file first
	Set ccqsfs_object = fso.CreateTextFile(ccqsfs_Absolute_script_name, True, False) ' *** vapoursynth fails with unicode input file *** [ filename, Overwrite[, Unicode]])
	If ccqsfs_object is Nothing  Then ' Something went wrong with creating the file
		If vrdtvsp_DEBUG Then WScript.StdOut.WriteLine("VRDTVSP DEBUG: VRDTVSP ERROR vrdtvsp_create_custom_QSF_vbscript_vrd_5_AND_6 - Error - Nothing object returned from fso.CreateTextFile for file """ & ccqsfs_Absolute_script_name & """... Aborting ...")
		WScript.StdOut.WriteLine("VRDTVSP vrdtvsp_create_custom_QSF_vbscript_vrd_5_AND_6 - Error - Nothing object returned from fso.CreateTextFile for file """ & ccqsfs_Absolute_script_name & """... Aborting ...")
		Wscript.Echo "Error 17 = cannot perform the requested operation"
		On Error goto 0
		WScript.Quit 17 ' Error 17 = cannot perform the requested operation
	End If
	For i = Lbound(ccqsfs) to UBound(ccqsfs) Step 1
		ccqsfs_object.WriteLine ccqsfs(i)
	Next
	ccqsfs_object.close
	Set ccqsfs_object = Nothing
	vrdtvsp_create_custom_QSF_vbscript_vrd_5_AND_6 = ccqsfs_Absolute_script_name
End Function

